vert-x3/vertx-mail-client

vertx-mail-client/src/main/asciidoc/groovy/index.adoc, vertx-mail-client/src/main/asciidoc/java/index.adoc, vertx-mail-client/src/main/asciidoc/js/index.adoc, vertx-mail-client/src/main/asciidoc/ruby/index.adoc, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPInitialDialogue.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/Utils.java, vertx-mail-client/src/main/resources/vertx-mail-js/mail_client.js, vertx-mail-client/src/test/java/io/vertx/ext/mail/HeloTest.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/MailFromSizeTest.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/impl/UtilsTest.java, vertx-mail-service/src/main/asciidoc/groovy/index.adoc, vertx-mail-service/src/main/asciidoc/java/index.adoc, vertx-mail-service/src/main/asciidoc/js/index.adoc, vertx-mail-service/src/main/asciidoc/ruby/index.adoc, vertx-mail-service/src/main/resources/vertx-mail-js/mail_client.js, vertx-mail-service/src/main/resources/vertx-mail-js/mail_service-proxy.js, vertx-mail-service/src/main/resources/vertx-mail-js/mail_service.js
moved isEsmtpSupported to Utils class, added unit test for the Utils method and a test in HeloTest
regenerated docs and generated js files
=> fix issue #46: ehloCmd method is not run when Mail Server reply "ESMTP" is not all uppercase characters

vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPInitialDialogue.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPSendMail.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPStarter.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/Utils.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/mailencoder/Utils.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/impl/SMTPConnectionPoolDummySMTPTest.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/impl/SMTPConnectionPoolShutdownTest.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/impl/SMTPConnectionPoolTest.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/mailencoder/MailEncoderTest.java
fix for issue #48, use executeBlocking for getHostname()
=> Issue48 hostnamenotasync

vertx-mail-client/src/main/java/io/vertx/ext/mail/mailencoder/Utils.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/mailencoder/MailEncoderTest.java
do not turn on quoted-printable encoding if the only char to be encoded in the text is tab
=> fix#60 tab is a valid character in unencoded mail text

vertx-mail-client/pom.xml, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/MailLocal2Test.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/MailLocalTest.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/SMTPTestWiser.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/impl/MailClientImpl2Test.java
fixes #72 
set hostname checking for TLS required and optional
fixed 2 unit test names
changed one unit test to integration test to avoid SSLSocketFactory jvm problem
=> Tls hostnamecheck missing

vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPConnection.java, vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/impl/ConnectionErrorPoolTest.java
decrease pool conn count when connection fails
add unit test with pool size 1, this hangs when trying two consecutive connections
=> fixes #77: when smtp connection is refused, the pool size count is wrong

vertx-mail-client/src/main/java/io/vertx/ext/mail/mailencoder/AttachmentPart.java, vertx-mail-client/src/test/java/io/vertx/ext/mail/mailencoder/MailEncoderTest.java
add encoding of attachment filename when there are utf8 chars in the filename
=> fixes issue#82: attachment filenames with non US-ASCII characters are garbled

vertx-mail-client/src/test/resources/certs/create_root.sh
the shell script to create the certs was missing the openssl.cnf file to start
=> copy openssl.cnf for first openssl operations

src/test/java/io/vertx/ext/mail/MailLocalTest.java, src/test/java/io/vertx/ext/mail/MailValidCertWrongHostTest.java
check cert error exceptions with general exception instead of DecoderException as this doesn't work anymore. The actual error is connection closed.
=> [fixes #96]

src/main/java/io/vertx/ext/mail/MailConfig.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, src/test/java/io/vertx/ext/mail/MailConfigTest.java
I need to ensure that the communication between the SMTP client and server is done through TLSv1.2. However the `MailConfig` currently has no way of setting it.
I added the property to the `MailConfig` and propagate it to the `NetClientOptions` of the `SMTPConnectionPool`.
It might be worth considering to include `NetClientOptions` as a member of the `MailConfig` directly to avoid duplicating more and more code. I didn't do it here because it would be a major change and I wanted to get feedback first.
=> Feature: Add enabled secure transport protocols to MailConfig

pom.xml, src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/enums.adoc, src/main/asciidoc/index.adoc, src/main/java/examples/MailExamples.java, src/main/java/io/vertx/ext/mail/DKIMSignAlgorithm.java, src/main/java/io/vertx/ext/mail/DKIMSignOptions.java, src/main/java/io/vertx/ext/mail/MailConfig.java, src/main/java/io/vertx/ext/mail/MessageCanonic.java, src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java, src/main/java/io/vertx/ext/mail/impl/SMTPSendMail.java, src/main/java/io/vertx/ext/mail/impl/dkim/DKIMSigner.java, src/main/java/io/vertx/ext/mail/mailencoder/AttachmentPart.java, src/main/java/io/vertx/ext/mail/mailencoder/EncodedPart.java, src/main/java/io/vertx/ext/mail/mailencoder/Utils.java, src/test/java/io/vertx/ext/mail/MailWithDKIMSignTest.java, src/test/java/io/vertx/ext/mail/impl/dkim/DKIMSignerTest.java
* Added DKIMSignOptions to specify options for DKIM signature
* Added james-jdkim to test scope for the signature verification tests
* Enable catch for Attachment's ReadStream in case DKIM is enabled
Signed-off-by: Lin Gao <aoingl@gmail.com>
Fixes: #102 
Feature RFC doc: https://github.com/gaol/vertx-mail-client/wiki/DKIM-Implementation
Summary of the PR:
* Added `DKIMSignOptions` to specify DKIM related configurations
* Added `enableDKIM` in MailConfig as well so that it can be disabled without losing configures.
* I am open to have `DKIMSignOptions` only in `MailConfig` as well.
* Updated docs about how to use it
=> [Issue-102] implement DKIM signature

src/main/java/io/vertx/ext/mail/impl/SMTPAuthentication.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, src/main/java/io/vertx/ext/mail/impl/SMTPStarter.java, src/main/java/io/vertx/ext/mail/impl/sasl/AuthOperationFactory.java, src/main/java/io/vertx/ext/mail/impl/sasl/AuthXOAUTH2.java, src/test/java/io/vertx/ext/mail/SMTPTestBase.java, src/test/java/io/vertx/ext/mail/impl/MailAuthChainTest.java, src/test/java/io/vertx/ext/mail/impl/sasl/AuthOperationFactoryTest.java
Fixes: #124 
Changes in the PR in summary:
* Try next authentication mechanism in preference order if current failed in SMTPAuthentication
* Remember the last successful authentication method as default on in AuthOperationFactory
* Update log level of XOAUTH2 to warning
* Revert the order between `LOGIN` and `PLAIN` in the preference order
* Added tests on auth failures
=> [Issue-124] Try next authentication mechanism if current one failed

.gitignore, src/test/java/io/vertx/ext/mail/MailAttachmentTest.java, src/test/java/io/vertx/ext/mail/MailMessageTest.java, src/test/java/io/vertx/ext/mail/SMTPTestBase.java
Fixes: #129 
Changes in the PR:
- Ignore `generated` from version control
- Fix test failures by removing the `=` padding according to the changes in vertx-core
- Log the warning message when the test will fail in case of testing exceptions.
=> [Issue-129] Fix test failures caused by JSON RFC

src/main/asciidoc/dataobjects.adoc, src/main/java/io/vertx/ext/mail/MailConfig.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, src/test/java/io/vertx/ext/mail/MailConfigTest.java
This allows for the setting of all of the options used to create the
connection to the SMTP server and not just the few that were exposed by
the MailConfig class.
Fixes #79
=> Make MailConfig a sub-class of NetClientOptions

src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/enums.adoc, src/main/asciidoc/index.adoc, src/main/java/io/vertx/ext/mail/CanonicalizationAlgorithm.java, src/main/java/io/vertx/ext/mail/DKIMSignOptions.java, src/main/java/io/vertx/ext/mail/impl/dkim/DKIMSigner.java, src/test/java/io/vertx/ext/mail/MailWithDKIMSignTest.java, src/test/java/io/vertx/ext/mail/impl/dkim/DKIMSignerTest.java
Fixes: #139 
`MessageCanonic.java` was introduced from `4.0.0.milestone4`, so it should be fine to rename it before next milestone and ga.
=> [Issue-193] Rename MessageCanonic to CanonicalizationAlgorithm

src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/index.adoc, src/main/java/io/vertx/ext/mail/MailConfig.java, src/main/java/io/vertx/ext/mail/impl/Capabilities.java, src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java, src/main/java/io/vertx/ext/mail/impl/MultilineParser.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnection.java, src/main/java/io/vertx/ext/mail/impl/SMTPSendMail.java, src/test/java/io/vertx/ext/mail/HeloTest.java, src/test/java/io/vertx/ext/mail/MailAuthTest.java, src/test/java/io/vertx/ext/mail/MailConfigTest.java, src/test/java/io/vertx/ext/mail/MailFromSizeTest.java, src/test/java/io/vertx/ext/mail/MailPoolServerClosesTest.java, src/test/java/io/vertx/ext/mail/MailValidCertWrongHostTest.java, src/test/java/io/vertx/ext/mail/TestSmtpServer.java, src/test/java/io/vertx/ext/mail/impl/CapabilitiesTest.java, src/test/java/io/vertx/ext/mail/impl/MailAuthChainTest.java, src/test/java/io/vertx/ext/mail/impl/MailPipeliningTest.java, src/test/java/io/vertx/ext/mail/impl/MultilineParserTest.java, src/test/java/io/vertx/ext/mail/impl/SMTPConnectionPoolDummySMTPTest.java
* Introduce pipelining in MailConfig
* futurize the SMTPSendMail implementation to adopt new extensions easier
* Fixed tests which has PIPELINING extension declared
* Added related tests
Motivation:
Fixes: #143 
This PR added support of `SMTP Pipelining` into the vertx-mail-client, so that it will reduce round-trips when SMTP server support `Pipelining`. It also provides the option to switch back to not using the `Pipelining`.
=> Support Pipelining

src/test/java/io/vertx/ext/mail/impl/MailSendContextTest.java
Motivation:
Fixes #125 
Looks like that current implementation already makes sure that [the call back handler is always called in the caller context](https://github.com/vert-x3/vertx-mail-client/blob/15d9c72c91fdffcb0426fa5cecc63c1014966359/src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java#L202), but without test to guarantee that, this PR added a test only to make sure it won't break the context model in the future development.
=> [ISSUE-125] Make sure the callback handler is always called in caller context

src/main/asciidoc/index.adoc, src/main/java/io/vertx/ext/mail/MailConfig.java, src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java, src/main/java/io/vertx/ext/mail/mailencoder/MailEncoder.java, src/test/java/io/vertx/ext/mail/mailencoder/MailEncoderTest.java
Motivation:
Fixes: #161 
This PR tries to add a new option `boolean multiPartOnly` into `MailConfig` as the trigger to roll back the Vert.x 3 behavior, which always sends mails as multipart format as long as the attachments is not null(even it is empty list). It defaults to `false` which checks the content to decide if the mail format is multipart or not.
To roll back the Vert.x 3 behavior, you need to call: `mailConfig.setMultiPartOnly(true)`.
Conformance:
=> [ISSUE-161] Format change between Vert.x 3 and 4

src/main/asciidoc/index.adoc, src/main/java/io/vertx/ext/mail/MailConfig.java, src/main/java/io/vertx/ext/mail/impl/SMTPAuthentication.java, src/main/java/io/vertx/ext/mail/impl/sasl/AuthOperation.java, src/main/java/io/vertx/ext/mail/impl/sasl/AuthOperationFactory.java, src/main/java/io/vertx/ext/mail/impl/sasl/NTLMAuth.java, src/main/java/io/vertx/ext/mail/impl/sasl/NTLMEngineException.java, src/main/java/io/vertx/ext/mail/impl/sasl/NTLMEngineImpl.java, src/test/java/io/vertx/ext/mail/impl/sasl/AuthNTLMTest.java, src/test/java/io/vertx/ext/mail/impl/sasl/AuthOperationFactoryTest.java
Motivation: Fixes #159 
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:
This PR tries to add NTLM authentication, it is still wildly used in Exchange server, one case is tracked by issue: #158 
This PR copied NTLMEngineImpl from [apache httpcomponents-client](https://github.com/apache/httpcomponents-client/blob/5.0.3-RC1/httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/NTLMEngineImpl.java) for generate NTLM type1 …
=> Support NTLM authentication

src/main/java/io/vertx/ext/mail/mailencoder/EmailAddress.java
Motivation:
Including name of invalid email address in the exception message would likely help someone to know whats really going on.
Conformance:
=> Includes name of invalid email in the exception message

src/main/java/io/vertx/ext/mail/impl/SMTPConnection.java
Motivation:
Fixes #175 
Conformance:
Some SMTP servers may close the TCP connection with `[RST, ACK]` sequence right after replying the `QUIT` SMTP command, which leads to client exception with `connection reset by peer`. logging the exception in debug only.
I don't see how I can mock the TCP termination, so this PR does not have tests included.
=> [Issue-175] Ignore the exception after quit has been sent

src/main/java/io/vertx/ext/mail/impl/SMTPConnection.java
Fix #186 
The error handler was set to null before we had a chance to report the error:
1. The server closes the connection
2. the handlers are clearer
3. the error is reported
The fix just keeps a reference on the error handler, so step 3 would report the failure correctly.
=> Fix error reporting when during an authentication chain, the connection is closed by the remote server

pom.xml
Reverts vert-x3/vertx-mail-client#192
for now we consistently use 2.17.1 everywhere in vertx when needed
=> Revert "Bump log4j2.version from 2.17.1 to 2.19.0"

src/main/java/io/vertx/ext/mail/SMTPException.java, src/main/java/io/vertx/ext/mail/impl/Capabilities.java, src/main/java/io/vertx/ext/mail/impl/SMTPAuthentication.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnection.java, src/main/java/io/vertx/ext/mail/impl/SMTPReset.java, src/main/java/io/vertx/ext/mail/impl/SMTPResponse.java, src/main/java/io/vertx/ext/mail/impl/SMTPSendMail.java, src/test/java/io/vertx/ext/mail/MailEnhancedStatusCodesTest.java, src/test/java/io/vertx/ext/mail/TestSmtpServer.java
Motivation:
Fixes #172 
Conformance:
This PR tries to add support for enhancement status code. When SMTP server support `ENHANCEDSTATUSCODES`, this client will try to parse the status code on exception, and `SMTPException.getCategory()` returns the category defined by https://datatracker.ietf.org/doc/html/rfc3463.
=> [Issue-172] Support enhanced status code

src/main/java/io/vertx/ext/mail/impl/MailAttachmentImpl.java, src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java, src/main/java/io/vertx/ext/mail/impl/SMTPAuthentication.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnection.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, src/main/java/io/vertx/ext/mail/impl/SMTPEndPoint.java, src/main/java/io/vertx/ext/mail/impl/SMTPInitialDialogue.java, src/main/java/io/vertx/ext/mail/impl/SMTPReset.java, src/main/java/io/vertx/ext/mail/impl/SMTPResponse.java, src/main/java/io/vertx/ext/mail/impl/SMTPSendMail.java, src/main/java/io/vertx/ext/mail/impl/SMTPStarter.java, src/main/java/io/vertx/ext/mail/impl/dkim/DKIMSigner.java, src/test/java/io/vertx/ext/mail/impl/SMTPConnectionPoolDummySMTPTest.java, src/test/java/io/vertx/ext/mail/impl/SMTPConnectionPoolShutdownTest.java, src/test/java/io/vertx/ext/mail/impl/SMTPConnectionPoolTest.java, src/test/java/io/vertx/ext/mail/impl/SMTPMaxCountPerConnTest.java
Motivation:
Even after the recent change (#207) to offer a future-based API, the mail client internals remained heavily callback-oriented, with some idiosyncratic quirks. This PR changes most of the implementation to be future-based, which allows a lot of code cleanup.
=> Replace callbacks with futures

src/main/java/io/vertx/ext/mail/mailencoder/Utils.java, src/test/java/io/vertx/ext/mail/MailSubjectTest.java, src/test/java/io/vertx/ext/mail/mailencoder/MailEncoderTest.java
Motivation:
Line folding should consider the Unicode that occupies more than one byte.
=> Header Unicode folding fix

src/main/java/io/vertx/ext/mail/mailencoder/Utils.java, src/test/java/io/vertx/ext/mail/AdditionalAsserts.java, src/test/java/io/vertx/ext/mail/SMTPTestBareLfMessageHandlerFactory.java, src/test/java/io/vertx/ext/mail/SMTPTestWiser.java, src/test/java/io/vertx/ext/mail/impl/SMTPSendMailTest.java, src/test/java/io/vertx/ext/mail/mailencoder/MailEncoderTest.java
Motivation:
fixes https://github.com/vert-x3/vertx-mail-client/issues/219 SMTP Smuggling problems
Replaces #220
Implementation Detail:
* As discussed in #219 the preferred way is to fix the Encoder instead of Replacing it in the SMTP Client.
This PR implements the required changes in the Encoder.
* The BareLF check is implemented as Wiser MessageHandler (as it was in #220)
* The error mainly occures in the header-section, so the test will set `Subject`, `From` and `To` to verify correct handling.
* Due to the changes in the Encoder, the MailEncoderTest has to be fixed, consider that `\r\n` is only introduced in length dependent breaking of the encoded words in [Utils.java](https://github.com/cs8898/vertx-mail-client/blob/fix/219-bare-LF-encoder/src/main/java/io/vertx/ext/mail/mailencoder/U …
=> FIX#219: bare <LF> received after DATA (encoder)

src/main/asciidoc/index.adoc, src/main/java/examples/MailExamples.java, src/main/java/io/vertx/ext/mail/MailClient.java, src/main/java/io/vertx/ext/mail/MailClientBuilder.java, src/main/java/io/vertx/ext/mail/impl/MailClientBuilderImpl.java, src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java, src/main/java/io/vertx/ext/mail/impl/SMTPAuthentication.java, src/main/java/io/vertx/ext/mail/impl/SMTPConnectionPool.java, src/main/java/io/vertx/ext/mail/impl/SMTPStarter.java, src/main/java/io/vertx/ext/mail/impl/sasl/AuthOperationFactory.java, src/test/java/io/vertx/tests/mail/client/MailAuthTest.java, src/test/java/io/vertx/tests/mail/client/SMTPTestBase.java, src/test/java/io/vertx/tests/mail/internal/sasl/AuthNTLMTest.java, src/test/java/io/vertx/tests/mail/internal/sasl/AuthOperationFactoryTest.java
In some production environments, credentials may be changed during the application lifetime (see https://github.com/quarkusio/quarkus/issues/39359)
This PR introduces a builder for the mail client.
With the builder, a user can set a supplier that provides fresh credentials asynchronously when required.
=> Support rotating credentials
